# Generated by Django 5.1.2 on 2024-10-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-update', '-created']},
        ),
    ]
